### ISSUE TITLE
I would like to know more about "charting"

### ISSUE THREAD

**Issue by gcuscc** [Suprnova123/Chunithm-Charting-Research#1]
This is a file taken from music0050_00.

I'm analyzing this, but it's difficult.
I will appreciate your help.

T_REC_TAP	8
T_REC_CHR	0
T_REC_FLK	0
T_REC_MNE	0
T_REC_HLD	11
T_REC_SLD	2
T_REC_AIR	6
T_REC_AHD	9
T_REC_ALL	36
T_NOTE_TAP	8
T_NOTE_CHR	0
T_NOTE_FLK	0
T_NOTE_MNE	0
T_NOTE_HLD	11
T_NOTE_SLD	2
T_NOTE_AIR	6
T_NOTE_AHD	3
T_NOTE_ALL	30
T_NUM_TAP	21
T_NUM_CHR	0
T_NUM_FLK	0
T_NUM_MNE	0
T_NUM_HLD	11
T_NUM_SLD	2
T_NUM_AIR	9
T_NUM_AHD	9
T_NUM_AAC	9
T_CHRTYPE_UP	0
T_CHRTYPE_DW	0
T_CHRTYPE_CE	0
T_LEN_HLD	11500
T_LEN_SLD	2000
T_LEN_AHD	33000
T_LEN_ALL	46500
T_JUDGE_TAP	21
T_JUDGE_HLD	8
T_JUDGE_SLD	8
T_JUDGE_AIR	115
T_JUDGE_FLK	0
T_JUDGE_ALL	152
T_FIRST_MSEC	29000
T_FIRST_RES	5568
T_FINAL_MSEC	205000
T_FINAL_RES	39360
T_PROG_00	2
T_PROG_05	4
T_PROG_10	0
T_PROG_15	2
T_PROG_20	0
T_PROG_25	5
T_PROG_30	5
T_PROG_35	10
T_PROG_40	0
T_PROG_45	0
T_PROG_50	4
T_PROG_55	0
T_PROG_60	8
T_PROG_65	0
T_PROG_70	9
T_PROG_75	25
T_PROG_80	2
T_PROG_85	30
T_PROG_90	12
T_PROG_95	34

**Comment by Suprnova** [comment]
Hey, I'm unsure exactly what the meaning of most of these are, although I think any of the T_REC and T_NOTE fields are counting the amount of notes of that specified type, although I don't know the difference between them. I think T_LEN refers to the duration that all of the notes are present throughout the chart (i.e. two 200 millisecond holds = T_LEN_HLD 400. I know that T_FIRST_MSEC is the first note in the chart in milliseconds and T_FIRST_RES is the first note in the chart in resolution. I also know that T_FINAL_MSEC is the last note in the chart in milliseconds and T_FINAL_RES is the last note in the chart in resolution.

It's worth mentioning that, from my experience, these tags do not have to be changed from an existing chart as a template when creating custom charts.
